version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    deploy:
      replicas: 4
    expose:
      - 8080
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 8080:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    network_mode: host
      